const tg = window.Telegram?.WebApp;
if (tg) {
  tg.ready(); tg.expand();
  tg.setHeaderColor?.('#09070f'); tg.setBackgroundColor?.('#09070f');
}
const app = document.getElementById('app');
let catalog={categories:[],products:[]}, me={has_access:false,discount:0,purchases:[]};
let admin=false, selectedChat=null, chatPoll=null, chatTimer=null, activeCategory='all', searchText='';
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0))+' ₽';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=(p,cls='product-img')=>p?.photo?`<img class="${cls}" src="${esc(p.photo)}" alt="" loading="lazy" onerror="this.outerHTML='<div class=\'${cls}\'>✦</div>'">`:`<div class="${cls}">✦</div>`;
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(tg?.initData)headers['X-Telegram-Init-Data']=tg.initData;const r=await fetch(path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка запроса');return d;}
function toast(text){if(tg?.showPopup){tg.showPopup({title:'BANNY SHOP',message:text,buttons:[{type:'ok'}]});}else{const x=document.createElement('div');x.className='toast';x.textContent=text;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}}
async function boot(){
  try{catalog=await api('/api/catalog')}catch(e){catalog={categories:[],products:[]}}
  if(tg?.initData){try{me=await api('/api/me')}catch(e){}}
  try{const s=await api('/api/admin/summary');admin=!!s.ok}catch(e){admin=false}
  home();
}
function setNav(tab){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));}
function categoryIcon(k){const icons=['✦','◈','◉','◆','✧','⬢'];let h=0;for(const c of String(k))h=(h+c.charCodeAt(0))%icons.length;return k==='banny_premium_v3'?'♛':icons[h]}
function catCount(c){return `${c.count} ${c.count===1?'товар':(c.count>=2&&c.count<=4?'товара':'товаров')}`}
function productCard(p){return `<article class="product-card" onclick="productPage('${esc(p.key)}')"><div class="product-media">${img(p)}<span class="media-glow"></span>${p.key==='banny_premium_v3'?'<span class="product-badge">PREMIUM</span>':''}</div><div class="product-body"><div class="product-cat">${esc((catalog.categories.find(c=>c.key===p.category_key)||{}).title||'BANNY SHOP')}</div><h3>${esc(p.title)}</h3><p>${esc(p.description||'Готовое решение для твоего проекта.')}</p><div class="product-bottom"><strong>${money(discounted(p.price))}</strong><button onclick="event.stopPropagation();checkoutPage('${esc(p.key)}')">Купить</button></div></div></article>`}
function categoryChip(c){return `<button class="chip ${activeCategory===c.key?'active':''}" onclick="setCategory('${esc(c.key)}')">${categoryIcon(c.key)} ${esc(c.title)} <span>${c.count}</span></button>`}
function filteredProducts(){let ps=catalog.products.filter(p=>activeCategory==='all'||p.category_key===activeCategory);if(searchText)ps=ps.filter(p=>`${p.title} ${p.description} ${p.functional}`.toLowerCase().includes(searchText));return ps}
function home(){stopChatPolling();setNav('home');activeCategory='all';searchText='';app.innerHTML=`<section class="page-enter"><div class="hero neon"><div class="hero-orb orb-a"></div><div class="hero-orb orb-b"></div><div class="eyebrow">✦ BANNY SHOP</div><h1>Твой цифровой<br><span>арсенал.</span></h1><p>Готовые решения, проекты и доступы — красиво, быстро и прямо в Telegram.</p><div class="hero-actions"><button class="hero-btn" onclick="categoriesPage()">Открыть каталог <b>→</b></button><span class="hero-note">⚡ мгновенная выдача после проверки</span></div></div><div class="section-head"><div><small class="section-kicker">КАТАЛОГ</small><h2>Категории</h2></div><button class="text-btn" onclick="categoriesPage()">Все →</button></div><div class="chips">${catalog.categories.map(categoryChip).join('')||'<span class="muted">Категории появятся здесь</span>'}</div><div class="section-head"><div><small class="section-kicker">SHOP</small><h2>Популярное</h2></div><span class="count-pill">${catalog.products.length}</span></div><div class="products-grid">${catalog.products.slice(0,6).map(productCard).join('')||emptyState('🛒','Товаров пока нет','Администратор ещё не добавил товары.')}</div>${admin?`<button class="admin-entry neon-border" onclick="adminHome()">👑 Открыть BANNY CONTROL</button>`:''}</section>`}
function setCategory(k){activeCategory=k;searchText='';renderCatalogPage()}
function categoriesPage(){setNav('categories');activeCategory='all';searchText='';renderCatalogPage()}
function renderCatalogPage(){setNav('categories');const ps=filteredProducts();app.innerHTML=`<section class="page-enter"><div class="catalog-title"><div><small class="section-kicker">КАТАЛОГ</small><h1>Все товары</h1></div><span class="count-pill">${ps.length}</span></div><div class="search-wrap"><span>⌕</span><input id="catalogSearch" value="${esc(searchText)}" placeholder="Поиск товара..." oninput="searchCatalog(this.value)"></div><div class="chips scroll-chips"><button class="chip ${activeCategory==='all'?'active':''}" onclick="setCategory('all')">✦ Все <span>${catalog.products.length}</span></button>${catalog.categories.map(categoryChip).join('')}</div><div class="products-grid">${ps.map(productCard).join('')||emptyState('⌕','Ничего не найдено','Попробуй другой запрос или категорию.')}</div></section>`}
function searchCatalog(v){searchText=(v||'').toLowerCase().trim();renderCatalogPage();setTimeout(()=>document.getElementById('catalogSearch')?.focus(),0)}
function categoryPage(k){activeCategory=k;searchText='';const c=catalog.categories.find(x=>x.key===k);renderCatalogPage();if(c){const h=app.querySelector('h1');if(h)h.textContent=c.title}}
function productPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;const c=catalog.categories.find(x=>x.key===p.category_key);app.innerHTML=`<section class="page-enter"><button class="back" onclick="${c?`categoryPage('${esc(c.key)}')`:'categoriesPage()'}">← Назад</button><div class="product-detail"><div class="detail-media">${img(p,'detail-img')}<div class="detail-shine"></div></div><div class="detail-cat">${categoryIcon(c?.key||'')} ${esc(c?.title||'BANNY SHOP')}</div><h1>${esc(p.title)}</h1><p class="detail-desc">${esc(p.description||'Описание отсутствует.')}</p><div class="detail-price"><div><small>Цена</small><strong>${money(discounted(p.price))}</strong>${me.discount?`<em>Промокод −${me.discount}%</em>`:''}</div><span>✓ Безопасная покупка</span></div><div class="detail-actions"><button class="btn primary" onclick="checkoutPage('${esc(k)}')">💳 Купить за ${money(discounted(p.price))}</button><button class="btn" onclick="functionalPage('${esc(k)}')">📋 Весь функционал</button><div class="action-row"><button class="btn" onclick="reviewsPage('${esc(k)}')">⭐ Отзывы</button><button class="btn" onclick="promoPage()">🎟 Промокод</button></div></div></div></section>`}
function discounted(p){return me.discount?Math.round(Number(p||0)*(1-Number(me.discount)/100)):Number(p||0)}
function functionalPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;app.innerHTML=`<section class="page-enter"><button class="back" onclick="productPage('${esc(k)}')">← К товару</button><div class="feature-head"><span>📋</span><div><small>ПОДРОБНО</small><h1>Функционал</h1></div></div><div class="feature-card">${esc(p.functional||'Функционал не указан.').replace(/\n/g,'<br>')}</div><button class="btn primary" onclick="checkoutPage('${esc(k)}')">Купить ${money(discounted(p.price))}</button></section>`}
function reviewsPage(k){app.innerHTML=`<section class="page-enter"><button class="back" onclick="productPage('${esc(k)}')">← Назад</button><div class="review-hero"><div class="rating">4.9</div><div class="stars">★★★★★</div><p>Реальные отзывы и результаты покупателей.</p></div><button class="btn primary" onclick="openTelegram('https://t.me/bannyotzv')">⭐ Открыть канал с отзывами</button></section>`}
function promoPage(){setNav('promo');app.innerHTML=`<section class="page-enter"><div class="section-kicker">BONUS</div><h1>Промокод</h1><p class="muted">Введи код и получи скидку на покупку.</p><div class="promo-card"><div class="promo-icon">🎟</div><input class="input" id="promo" placeholder="BANNY2026"><button class="btn primary" onclick="activatePromo()">Активировать</button></div>${me.discount?`<div class="success-card"><b>−${me.discount}%</b><span>Скидка активна</span></div>`:''}</section>`}
async function activatePromo(){const code=document.getElementById('promo')?.value.trim().toUpperCase();if(!code)return;try{const r=await api('/api/promo',{method:'POST',body:JSON.stringify({code})});me.discount=r.discount||0;toast(`Скидка ${me.discount}% активирована`);promoPage()}catch(e){toast('Промокод не найден')}}
function checkoutPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;app.innerHTML=`<section class="page-enter"><button class="back" onclick="productPage('${esc(k)}')">← Назад</button><div class="checkout"><div class="checkout-head"><span class="secure">🔐</span><div><b>Безопасное оформление</b><small>Заказ привязан к Telegram</small></div></div><div class="order-card">${img(p,'mini-img')}<div class="grow"><b>${esc(p.title)}</b><small>1 товар</small></div><strong>${money(discounted(p.price))}</strong></div><h2>Способ оплаты</h2><div class="pay-methods"><button class="pay-method active" data-method="card" onclick="selectMethod(this)">💳 Карта / перевод<small>Реквизиты появятся после заказа</small></button><button class="pay-method" data-method="sbp" onclick="selectMethod(this)">⚡ СБП<small>Быстрый перевод</small></button><button class="pay-method" data-method="stars" onclick="selectMethod(this)">⭐ Telegram Stars<small>Если провайдер подключён</small></button></div><div class="checkout-total"><span>Итого</span><strong>${money(discounted(p.price))}</strong></div><button class="btn primary" onclick="startPayment('${esc(k)}')">Оплатить ${money(discounted(p.price))}</button><p class="checkout-note">После оплаты отправь чек в бот. Администратор проверит его и выдаст доступ.</p></div></section>`}
function selectMethod(el){document.querySelectorAll('.pay-method').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
async function startPayment(k){const p=catalog.products.find(x=>x.key===k);const method=document.querySelector('.pay-method.active')?.dataset.method||'card';try{const r=await api('/api/buy',{method:'POST',body:JSON.stringify({product:k,payment_method:method})});statusPage(r.order_id,p)}catch(e){toast(e.message==='already_owned'?'Товар уже куплен.':'Не удалось создать заказ.')}}
function statusPage(orderId,p){app.innerHTML=`<section class="page-enter status-page"><div class="status-icon">✓</div><div class="eyebrow">ЗАКАЗ #${esc(orderId)}</div><h1>Оплата создана</h1><p class="muted">${esc(p.title)}</p><div class="requisites"><b>РЕКВИЗИТЫ</b><div>Карта [МИР]<code>2204120135107775</code></div><div>Банк <strong>YooMoney</strong></div><small>Переведи точную сумму и отправь фото чека в чат с ботом.</small></div><div id="statusSteps" class="status-steps"></div><div id="statusCard" class="order-status-card"></div><button class="btn primary" onclick="sendReceiptToBot()">📸 Отправить чек в бота</button><button class="btn outline" onclick="home()">В магазин</button></section>`;window.currentOrderId=orderId;pollOrder(orderId,p)}
function sendReceiptToBot(){if(tg?.close){toast('Открой чат бота и отправь фото чека');setTimeout(()=>tg.close(),700)}else{toast('Открой чат бота и отправь фото чека')}}
async function pollOrder(id,p){clearInterval(chatTimer);let tries=0;const render=o=>{const st=o.status==='paid'?2:o.status==='checking'?1:0;document.getElementById('statusSteps').innerHTML=[['Оплата','💳'],['Проверка','🔎'],['Готово','✓']].map((x,i)=>`<div class="status-step ${i<=st?'done':''}"><span>${i<=st?x[1]:'•'}</span><b>${x[0]}</b></div>${i<2?'<i></i>':''}`).join('');const labels={paying:'Ожидает оплату',checking:'Проверяем чек',paid:'Оплата подтверждена',rejected:'Чек отклонён'};document.getElementById('statusCard').innerHTML=`<span class="status-pill">${labels[o.status]||o.status}</span><small>Сумма заказа</small><strong>${money(o.amount)}</strong><p>${o.status==='paid'?'Доступ будет выдан ботом.':o.status==='rejected'?'Отправь новый чек в бот.':'После перевода отправь фото чека в бот.'}</p>`};const tick=async()=>{try{const r=await api('/api/order/'+encodeURIComponent(id));render(r.order);if(['paid','rejected'].includes(r.order.status)||tries++>90)clearInterval(chatTimer)}catch(e){}};await tick();chatTimer=setInterval(tick,2000)}
async function purchases(){setNav('purchases');try{me=await api('/api/me')}catch(e){}const list=me.purchases||[];app.innerHTML=`<section class="page-enter"><div class="section-kicker">YOUR LIBRARY</div><h1>Мои покупки</h1>${me.has_access?'<div class="access-card"><span>✓</span><div><b>Доступ активен</b><small>BANNY PREMIUM</small></div></div>':''}<div class="purchase-list">${list.length?list.map(x=>`<div class="purchase-row"><div class="mini-icon">✦</div><div class="grow"><b>${esc(x.title||x.product)}</b><small>${esc(x.date||'')}</small></div><span class="badge">Оплачено</span></div>`).join(''):emptyState('🛍','Покупок пока нет','Здесь появятся твои оплаченные товары.')}</div></section>`}
function profile(){setNav('profile');const u=tg?.initDataUnsafe?.user;const name=u?[u.first_name,u.last_name].filter(Boolean).join(' '):'Telegram пользователь';app.innerHTML=`<section class="page-enter"><div class="profile-cover"><div class="profile-orb"></div><div class="avatar big">${esc((u?.first_name||'B')[0])}</div><div class="profile-name"><h1>${esc(name)}</h1><small>${u?.username?'@'+esc(u.username):'BANNY USER'}</small></div><span class="badge">${me.has_access?'PREMIUM':'USER'}</span></div><div class="profile-menu"><button onclick="purchases()"><span>🛍</span><div><b>Мои покупки</b><small>История заказов</small></div>›</button><button onclick="promoPage()"><span>🎟</span><div><b>Промокод</b><small>Активировать скидку</small></div>›</button><button onclick="openTelegram('https://t.me/dev_tokio')"><span>💬</span><div><b>Поддержка</b><small>Связаться с админом</small></div>›</button></div>${admin?`<button class="admin-entry neon-border" onclick="adminHome()">👑 BANNY CONTROL · Админ-панель</button>`:''}</section>`}
function openTelegram(url){tg?.openTelegramLink?tg.openTelegramLink(url):window.open(url,'_blank')}
function emptyState(icon,title,text){return `<div class="empty-state"><div>${icon}</div><b>${title}</b><small>${text}</small></div>`}

async function adminHome(){if(!admin)return;stopChatPolling();setNav('profile');let s={};try{s=await api('/api/admin/summary')}catch(e){}app.innerHTML=`<section class="page-enter admin-page"><div class="admin-brand"><span>👑 BANNY CONTROL</span><small>Панель управления магазином</small></div><div class="admin-top"><button class="back" onclick="home()">← Магазин</button><button class="icon-btn" onclick="adminHome()">↻</button></div><div class="admin-stats"><div><b>${s.users||0}</b><small>Юзеров</small></div><div><b>${s.paid_users||0}</b><small>Доступ</small></div><div><b>${s.pending||0}</b><small>Проверка</small></div><div><b>${s.orders||0}</b><small>Заказы</small></div></div><div class="admin-grid"><button onclick="adminCatalog()"><span>🛒</span><b>Магазин</b><small>Категории и товары</small></button><button onclick="adminChats()"><span>💬</span><b>Чаты</b><small>Поддержка и сообщения</small></button><button onclick="adminUsers()"><span>👥</span><b>Пользователи</b><small>Поиск и профили</small></button><button onclick="adminOrders()"><span>🧾</span><b>Заказы</b><small>Статусы и оплаты</small></button><button onclick="adminPromo()"><span>🎟</span><b>Промокоды</b><small>Создать скидку</small></button><button onclick="openTelegram('https://t.me/dev_tokio')"><span>⚙️</span><b>Поддержка</b><small>Связь с разработчиком</small></button></div></section>`}
async function adminCatalog(){const r=await api('/api/catalog');catalog=r;app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminHome()">← Админка</button><div class="admin-title"><div><small>STORE MANAGER</small><h1>Магазин</h1></div><button class="btn compact primary" onclick="adminAddCategory()">＋ Категория</button></div>${catalog.categories.map(c=>`<div class="admin-category"><div class="admin-cat-head"><div class="cat-icon">${categoryIcon(c.key)}</div><div class="grow"><b>${esc(c.title)}</b><small>${esc(c.description||'Без описания')}</small></div><span>${c.count}</span></div><div class="admin-products">${catalog.products.filter(p=>p.category_key===c.key).map(p=>`<div class="admin-product">${img(p,'mini-img')}<div class="grow"><b>${esc(p.title)}</b><small>${money(p.price)}</small></div></div>`).join('')||'<small class="muted">Товаров нет</small>'}</div><button class="btn small-btn" onclick="adminAddProduct('${esc(c.key)}')">＋ Добавить товар</button></div>`).join('')}`}
function adminAddCategory(){app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminCatalog()">← Магазин</button><small class="section-kicker">STORE MANAGER</small><h1>Новая категория</h1><div class="form-card"><label>Название<input id="catTitle" class="input" placeholder="Lua решения"></label><label>Описание<textarea id="catDesc" class="input" placeholder="Готовые Lua-решения"></textarea></label><button class="btn primary" onclick="createCategory()">Создать категорию</button></div></section>`}
async function createCategory(){const title=document.getElementById('catTitle')?.value.trim(),description=document.getElementById('catDesc')?.value.trim();if(!title)return toast('Укажи название');try{await api('/api/admin/category',{method:'POST',body:JSON.stringify({title,description})});toast('Категория создана');await adminCatalog()}catch(e){toast('Не удалось создать категорию')}}
function adminAddProduct(categoryKey=''){app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminCatalog()">← Магазин</button><small class="section-kicker">STORE MANAGER</small><h1>Новый товар</h1><div class="form-card"><label>Категория<select id="productCategory" class="input">${catalog.categories.map(c=>`<option value="${esc(c.key)}" ${c.key===categoryKey?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label><label>Название<input id="productTitle" class="input" placeholder="Название товара"></label><label>Цена, ₽<input id="productPrice" type="number" min="0" class="input" placeholder="699"></label><label>Короткое описание<textarea id="productDesc" class="input" placeholder="Показывается на карточке"></textarea></label><label>Весь функционал<textarea id="productFunctional" class="input tall" placeholder="Полный список возможностей"></textarea></label><label>Фото (необязательно)<input id="productPhoto" class="input" placeholder="https://.../image.jpg"><small>Можно вставить прямую ссылку на картинку. Для локального фото используй создание товара через бота.</small></label><button class="btn primary" onclick="createProduct()">Создать товар</button></div></section>`}
async function createProduct(){const payload={category_key:document.getElementById('productCategory')?.value,title:document.getElementById('productTitle')?.value.trim(),price:Number(document.getElementById('productPrice')?.value||0),description:document.getElementById('productDesc')?.value.trim(),functional:document.getElementById('productFunctional')?.value.trim(),photo:document.getElementById('productPhoto')?.value.trim()};if(!payload.title||!payload.price||!payload.description||!payload.functional)return toast('Заполни все обязательные поля');try{await api('/api/admin/product',{method:'POST',body:JSON.stringify(payload)});toast('Товар создан');await adminCatalog()}catch(e){toast('Не удалось создать товар')}}
async function adminPromo(){app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminHome()">← Админка</button><small class="section-kicker">BONUS MANAGER</small><h1>Промокоды</h1><div class="form-card"><label>Код<input id="promoCode" class="input" placeholder="BANNY50"></label><label>Скидка, %<input id="promoDiscount" type="number" min="1" max="100" class="input" placeholder="50"></label><button class="btn primary" onclick="createPromo()">Создать промокод</button></div></section>`}
async function createPromo(){const code=document.getElementById('promoCode')?.value.trim().toUpperCase(),discount=Number(document.getElementById('promoDiscount')?.value||0);if(!code||discount<1||discount>100)return toast('Проверь код и скидку');try{await api('/api/admin/promo',{method:'POST',body:JSON.stringify({code,discount})});toast('Промокод создан');adminHome()}catch(e){toast('Не удалось создать промокод')}}
async function adminUsers(){stopChatPolling();const r=await api('/api/admin/users');app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminHome()">← Админка</button><div class="admin-title"><div><small>USERS</small><h1>Пользователи</h1></div><span class="count-pill">${r.users.length}</span></div><input id="usersSearch" class="input" placeholder="Имя, @username или ID" oninput="filterUsers(this.value)"><div id="usersList" class="list admin-list">${r.users.map(userRow).join('')||emptyState('👥','Пока пусто','Пользователей ещё нет.')}</div></section>`}
function userRow(u){return `<div class="user-row" data-search="${esc([u.first_name,u.last_name,u.username,u.id].filter(Boolean).join(' ').toLowerCase())}" onclick="openChat(${u.id})"><div class="avatar small">${esc((u.first_name||u.username||'U')[0])}</div><div class="grow"><b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени')}</b><small>${u.username?'@'+esc(u.username)+' · ':''}ID ${u.id}</small>${u.last_message?`<small class="preview">${esc(u.last_message)}</small>`:''}</div>${u.unread?`<span class="unread">${u.unread}</span>`:''}<span class="status-dot ${u.has_access?'on':''}"></span></div>`}
function filterUsers(q){q=(q||'').toLowerCase().trim();document.querySelectorAll('#usersList .user-row').forEach(x=>x.style.display=x.dataset.search.includes(q)?'flex':'none')}
async function adminChats(){stopChatPolling();const r=await api('/api/admin/users');const users=[...r.users].sort((a,b)=>(b.unread-a.unread)||String(b.last_message_at||b.last_seen||'').localeCompare(String(a.last_message_at||a.last_seen||'')));app.innerHTML=`<section class="page-enter admin-page chat-page"><div class="chat-layout"><aside class="chat-list"><div class="chat-top"><button class="back" onclick="adminHome()">←</button><div class="grow"><b>Чаты</b><small>${users.length} пользователей</small></div></div><input id="chatSearch" class="input" placeholder="Поиск чата" oninput="filterChats(this.value)"><div id="chatUsers">${users.map(chatUserRow).join('')||emptyState('💬','Диалогов нет','Новые сообщения появятся здесь.')}</div></aside><section class="chat-window" id="chatWindow"><div class="chat-empty">Выбери пользователя</div></section></div></section>`}
function chatUserRow(u){return `<div class="chat-user ${selectedChat===u.id?'selected':''}" data-search="${esc([u.first_name,u.last_name,u.username,u.id,u.last_message].filter(Boolean).join(' ').toLowerCase())}" onclick="openChat(${u.id})"><div class="avatar small">${esc((u.first_name||u.username||'U')[0])}</div><div class="grow"><div class="chat-user-line"><b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени')}</b>${u.last_message_at?`<time>${esc(u.last_message_at.slice(11,16))}</time>`:''}</div><small>${u.last_message?esc(u.last_message):(u.username?'@'+esc(u.username):'ID '+u.id)}</small></div>${u.unread?`<span class="unread">${u.unread}</span>`:''}</div>`}
function filterChats(q){q=(q||'').toLowerCase().trim();document.querySelectorAll('.chat-user').forEach(x=>x.style.display=x.dataset.search.includes(q)?'flex':'none')}
async function openChat(uid){selectedChat=uid;stopChatPolling();try{await api('/api/admin/chat/read',{method:'POST',body:JSON.stringify({user_id:uid})})}catch(e){}const r=await api('/api/admin/chats/'+uid);renderChat(r);startChatPolling()}
function renderChat(r){const u=r.user||{},name=[u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени';app.querySelector('#chatWindow').innerHTML=`<div class="chat-header"><button class="back mobile-only" onclick="adminChats()">←</button><div class="avatar small">${esc((u.first_name||u.username||'U')[0])}</div><div class="grow"><b>${esc(name)}</b><small>${u.username?'@'+esc(u.username)+' · ':''}ID ${u.id} · ${u.has_access?'доступ есть':'доступа нет'}</small></div><button class="chat-info" onclick="showUserInfo(${u.id})">ⓘ</button></div><div id="messages" class="messages">${r.messages.map(messageBubble).join('')||'<div class="chat-empty">Сообщений пока нет</div>'}</div><form class="chat-compose" onsubmit="sendChat(event)"><input id="chatInput" class="input" autocomplete="off" placeholder="Написать сообщение..."><button class="btn primary compact">➤</button></form>`;scrollChat()}
function messageBubble(m){return `<div class="bubble-wrap ${m.sender==='admin'?'out':'in'}"><div class="bubble">${esc(m.text||'').replace(/\n/g,'<br>')}<small>${esc(m.created_at||'')}</small></div></div>`}
function scrollChat(){const x=document.getElementById('messages');if(x)x.scrollTop=x.scrollHeight}
async function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text||!selectedChat)return;input.disabled=true;try{await api('/api/admin/chat/send',{method:'POST',body:JSON.stringify({user_id:selectedChat,text})});input.value='';await refreshOpenChat(false)}catch(err){toast('Не удалось отправить')}finally{input.disabled=false;input.focus()}}
async function refreshOpenChat(keep=true){if(!selectedChat)return;try{const r=await api('/api/admin/chats/'+selectedChat),box=document.getElementById('messages');if(!box)return;const bottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=r.messages.map(messageBubble).join('')||'<div class="chat-empty">Сообщений пока нет</div>';if(!keep||bottom)scrollChat()}catch(e){}}
function startChatPolling(){clearInterval(chatPoll);chatPoll=setInterval(async()=>{await refreshOpenChat(true);await refreshChatList()},2500)}
function stopChatPolling(){clearInterval(chatPoll);chatPoll=null;clearInterval(chatTimer);chatTimer=null}
async function refreshChatList(){const box=document.getElementById('chatUsers');if(!box)return;try{const r=await api('/api/admin/users');const q=(document.getElementById('chatSearch')?.value||'').toLowerCase().trim();box.innerHTML=r.users.map(chatUserRow).join('')||'<div class="chat-empty">Диалогов пока нет</div>';filterChats(q)}catch(e){}}
async function showUserInfo(uid){try{const r=await api('/api/admin/chats/'+uid);const u=r.user||{};const x=await api('/api/admin/orders');const orders=(x.orders||[]).filter(o=>Number(o.user_id)===Number(uid));toast(`${[u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени'} · ID ${u.id} · заказов ${orders.length}`)}catch(e){}}
async function adminOrders(){stopChatPolling();const r=await api('/api/admin/orders');app.innerHTML=`<section class="page-enter admin-page"><button class="back" onclick="adminHome()">← Админка</button><div class="admin-title"><div><small>PAYMENTS</small><h1>Заказы</h1></div><span class="count-pill">${r.orders.length}</span></div><div class="orders-list">${r.orders.map(o=>`<div class="order-admin"><div class="order-admin-top"><b>${esc(o.title)}</b><span class="status-pill">${esc(o.status)}</span></div><small>${esc([o.first_name,o.username?'@'+o.username:''].filter(Boolean).join(' · '))} · ID ${o.user_id}</small><strong>${money(o.amount)}</strong><small>${esc(o.created_at||'')}</small></div>`).join('')||emptyState('🧾','Заказов нет','Пока никто ничего не покупал.')}</div></section>`}

document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>({home,categories:categoriesPage,purchases,promo:promoPage,profile}[b.dataset.tab])()));
document.getElementById('closeBtn').onclick=()=>tg?.close?.();
boot();
