const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor?.(tg.themeParams?.header_bg_color || '#090a10'); tg.setBackgroundColor?.(tg.themeParams?.bg_color || '#090a10'); }
const app=document.getElementById('app');
let catalog={categories:[],products:[]}, me={has_access:false,discount:0,purchases:[]}, admin=false, selectedChat=null, chatTimer=null, chatPoll=null;
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0))+' ₽';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=(p,cls='product-img')=>p.photo?`<img class="${cls}" src="${esc(p.photo)}" alt="">`:`<div class="${cls}">◉</div>`;
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(tg?.initData)headers['X-Telegram-Init-Data']=tg.initData;const r=await fetch(path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка запроса');return d;}
async function boot(){try{catalog=await api('/api/catalog')}catch(e){}if(tg?.initData){try{me=await api('/api/me')}catch(e){}}try{const s=await api('/api/admin/summary');admin=!!s.ok}catch(e){admin=false}home();}
function setNav(tab){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));}
function categoryIcon(k){return k==='banny_premium_v3'?'♛':'✦'}
function productRow(p){return `<div class="row" onclick="productPage('${esc(p.key)}')">${p.photo?img(p,'mini-img'):'<div class="mini-img">◉</div>'}<div class="grow"><b>${esc(p.title)}</b><small>${esc(p.description||'Без описания')}</small><div class="price">${money(p.price)}</div></div><span class="arrow">›</span></div>`}
function home(){clearInterval(chatPoll);clearInterval(chatTimer);setNav('home');const cats=catalog.categories.slice(0,4);app.innerHTML=`<section><div class="hero"><div class="eyebrow">BANNY SHOP</div><h1>PREMIUM<br><span style="color:#a85cff">DIGITAL STORE</span></h1><p>Товары, готовые решения и проекты — прямо внутри Telegram.</p></div><div class="section-head"><h2>Категории</h2><button onclick="categoriesPage()">Все</button></div><div class="grid">${cats.map(c=>`<div class="cat" onclick="categoryPage('${esc(c.key)}')"><div class="icon">${categoryIcon(c.key)}</div><b>${esc(c.title)}</b><small>${c.count} товар${c.count===1?'':'ов'}</small></div>`).join('')}</div><div class="section-head"><h2>Популярное</h2></div><div class="list">${catalog.products.slice(0,5).map(productRow).join('')||'<div class="empty">Товаров пока нет.</div>'}</div>${admin?`<button class="admin-entry" onclick="adminHome()">👑 Открыть админ-панель</button>`:''}</section>`}
function categoriesPage(){setNav('categories');app.innerHTML=`<h1>Категории</h1><div class="list" style="margin-top:18px">${catalog.categories.map(c=>`<div class="row" onclick="categoryPage('${esc(c.key)}')"><div class="mini-img">${categoryIcon(c.key)}</div><div class="grow"><b>${esc(c.title)}</b><small>${c.count} товар${c.count===1?'':'ов'}</small></div><span class="arrow">›</span></div>`).join('')||'<div class="empty">Категорий пока нет.</div>'}</div>`}
function categoryPage(k){setNav('categories');const c=catalog.categories.find(x=>x.key===k),ps=catalog.products.filter(p=>p.key==='banny_premium_v3'?k==='banny_premium_v3':p.category_key===k||p.category===k);app.innerHTML=`<button class="back" onclick="categoriesPage()">← Назад</button><h1>${esc(c?.title||k)}</h1><p class="muted">${ps.length} товар${ps.length===1?'':'ов'}</p><div class="list" style="margin-top:18px">${ps.map(productRow).join('')||'<div class="empty">Пусто.</div>'}</div>`}
function productPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;const b=p.category_key||p.category;app.innerHTML=`<button class="back" onclick="${b?`categoryPage('${esc(b)}')`:'home()'}">← Назад</button><div class="detail">${img(p,'detail-img')}<h1>${esc(p.title)}</h1><p class="detail-desc">${esc(p.description||'Описание отсутствует.')}</p><div class="price-box"><small>Цена</small><strong>${money(discounted(p.price))}</strong>${me.discount?`<small>Промокод: −${me.discount}%</small>`:''}</div><div class="actions"><button class="btn primary" onclick="checkoutPage('${esc(k)}')">💳 Купить за ${money(discounted(p.price))}</button><button class="btn" onclick="functionalPage('${esc(k)}')">📋 Весь функционал</button><button class="btn" onclick="reviewsPage('${esc(k)}')">⭐ Отзывы</button><button class="btn" onclick="promoPage()">🎟 Промокод</button></div></div>`}
function discounted(p){return me.discount?Math.round(Number(p||0)*(1-Number(me.discount)/100)):Number(p||0)}
function functionalPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;app.innerHTML=`<button class="back" onclick="productPage('${esc(k)}')">← Назад</button><h2>${esc(p.title)} — <span style="color:#b16cff">ФУНКЦИОНАЛ</span></h2><hr style="border-color:#492766;margin:20px 0"><div class="feature-text">${esc(p.functional||'Функционал не указан.').replace(/\n/g,'<br>')}</div><div class="actions"><button class="btn outline" onclick="productPage('${esc(k)}')">← К товару</button></div>`}
function reviewsPage(k){app.innerHTML=`<button class="back" onclick="productPage('${esc(k)}')">← Назад</button><h2>⭐ Отзывы</h2><div class="rating">4.9</div><div class="stars">★★★★★</div><p class="muted">Отзывы публикуются в официальном канале.</p><div class="actions"><button class="btn primary" onclick="openTelegram('https://t.me/bannyotzv')">Открыть отзывы</button></div>`}
function promoPage(){setNav('promo');app.innerHTML=`<h1>Промокоды</h1><div class="section-head"><h2>Введите код</h2></div><div class="promo-line"><input class="input" id="promo" placeholder="BANNY2026"><button class="btn primary compact" onclick="activatePromo()">OK</button></div>${me.discount?`<div class="profile-card"><b>−${me.discount}%</b><p class="muted">Скидка активна.</p></div>`:''}`}
async function activatePromo(){const code=document.getElementById('promo')?.value.trim().toUpperCase();if(!code)return;try{const r=await api('/api/promo',{method:'POST',body:JSON.stringify({code})});me.discount=r.discount||0;tg?.showPopup?.({title:'Готово',message:`Скидка ${me.discount}% активирована.`,buttons:[{type:'ok'}]});promoPage()}catch(e){alert('Промокод не найден')}}
function checkoutPage(k){const p=catalog.products.find(x=>x.key===k);if(!p)return;app.innerHTML=`<button class="back" onclick="productPage('${esc(k)}')">← Назад</button><div class="checkout"><div class="checkout-head"><div class="checkout-lock">🔐</div><div><b>Оформление заказа</b><small>Заказ будет привязан к вашему Telegram</small></div></div><div class="order-card">${img(p,'mini-img')}<div class="grow"><b>${esc(p.title)}</b><small>Количество: 1</small></div><strong>${money(discounted(p.price))}</strong></div><div class="section-head"><h2>Способ оплаты</h2></div><div class="pay-methods"><button class="pay-method active" data-method="card" onclick="selectMethod(this)">💳 Банковская карта<small>Оплата переводом / реквизитами</small></button><button class="pay-method" data-method="sbp" onclick="selectMethod(this)">⚡ СБП<small>Быстрый перевод</small></button><button class="pay-method" data-method="stars" onclick="selectMethod(this)">⭐ Telegram Stars<small>Поддержка Stars при подключении провайдера</small></button></div><div class="checkout-total"><span>Итого</span><strong>${money(discounted(p.price))}</strong></div><button class="btn primary" onclick="startPayment('${esc(k)}')">Оплатить ${money(discounted(p.price))}</button><p class="checkout-note">После отправки чека заказ перейдёт в «Проверяется». После подтверждения администратором — «Оплачено».</p></div>`}
function selectMethod(el){document.querySelectorAll('.pay-method').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
async function startPayment(k){const p=catalog.products.find(x=>x.key===k);const method=document.querySelector('.pay-method.active')?.dataset.method||'card';try{const r=await api('/api/buy',{method:'POST',body:JSON.stringify({product:k,payment_method:method})});statusPage(r.order_id,p)}catch(e){alert(e.message==='already_owned'?'Товар уже куплен.':'Не удалось создать заказ.')}}
function statusPage(orderId,p){app.innerHTML=`<div class="status-page"><div class="status-icon">💳</div><h1>Заказ #${esc(orderId)}</h1><p class="muted">${esc(p.title)}</p><div class="requisites"><b>✅ РЕКВИЗИТЫ</b><div>Карта <strong>[МИР]</strong><br><code>2204120135107775</code></div><div>Банк: <strong>YooMoney</strong></div><small>После перевода отправьте фото чека в чат с ботом. Администратор проверит его вручную.</small></div><div id="statusSteps" class="status-steps"></div><div id="statusCard" class="order-status-card"></div><button class="btn primary" onclick="sendReceiptToBot()">📸 Отправить чек в бота</button><button class="btn outline" onclick="home()">В магазин</button></div>`;window.currentOrderId=orderId;pollOrder(orderId,p)}
function sendReceiptToBot(){tg?.close?.();}
async function pollOrder(id,p){clearInterval(chatTimer);let tries=0;const render=o=>{const st=o.status==='paid'?2:o.status==='checking'?1:0;document.getElementById('statusSteps').innerHTML=[['Оплата','💳'],['Проверка','🔎'],['Оплачено','✓']].map((x,i)=>`<div class="status-step ${i<=st?'done':''}"><span>${i<=st?x[1]:'•'}</span><b>${x[0]}</b></div>${i<2?`<div class="status-line ${i<st?'done':''}"></div>`:''}`).join('');const labels={paying:'Оплата создаётся',checking:'Чек проверяется',paid:'Оплата подтверждена',rejected:'Оплата отклонена'};document.getElementById('statusCard').innerHTML=`<span class="status-pill">${labels[o.status]||o.status}</span><small>Сумма</small><strong>${money(o.amount)}</strong><small style="margin-top:8px">${o.status==='paid'?'Доступ будет выдан ботом.':o.status==='rejected'?'Отправьте новый чек боту.':'Бот уже прислал реквизиты. Отправьте чек в чат.'}</small>`};const tick=async()=>{try{const r=await api('/api/order/'+encodeURIComponent(id));render(r.order);if(['paid','rejected'].includes(r.order.status)||tries++>90)clearInterval(chatTimer)}catch(e){}};await tick();chatTimer=setInterval(tick,2000)}
async function purchases(){setNav('purchases');try{me=await api('/api/me')}catch(e){}const list=me.purchases||[];app.innerHTML=`<h1>Мои покупки</h1>${me.has_access?'<div class="profile-card"><b>✅ Доступ активен</b><p class="muted">BANNY PREMIUM</p></div>':''}<div class="list">${list.length?list.map(x=>`<div class="row"><div class="grow"><b>${esc(x.title||x.product)}</b><small>${esc(x.date||'')}</small></div><span class="badge">Оплачено</span></div>`).join(''):'<div class="empty">История покупок пуста.</div>'}</div>`}
function profile(){setNav('profile');const u=tg?.initDataUnsafe?.user,name=u?[u.first_name,u.last_name].filter(Boolean).join(' '):'Telegram пользователь';app.innerHTML=`<h1>Профиль</h1><div class="profile-card"><div class="profile-top"><div class="avatar">${esc((u?.first_name||'B')[0])}</div><div><b>${esc(name)}</b><small class="muted" style="display:block">${u?.username?'@'+esc(u.username):''}</small><span class="badge">${me.has_access?'Доступ активен':'Покупок пока нет'}</span></div></div></div><div class="list"><div class="row" onclick="purchases()"><div class="grow"><b>🛍 Мои покупки</b></div><span>›</span></div><div class="row" onclick="promoPage()"><div class="grow"><b>🎟 Промокод</b></div><span>›</span></div><div class="row" onclick="openTelegram('https://t.me/dev_tokio')"><div class="grow"><b>👨‍💻 Поддержка</b></div><span>›</span></div></div>${admin?`<button class="admin-entry" onclick="adminHome()">👑 Админ-панель</button>`:''}`}
function openTelegram(url){tg?.openTelegramLink?tg.openTelegramLink(url):window.open(url,'_blank')}
async function adminHome(){
  if(!admin)return;
  stopChatPolling();
  setNav('profile');
  let s={};try{s=await api('/api/admin/summary')}catch(e){}
  app.innerHTML=`<div class="admin-head"><button class="back" onclick="home()">← Магазин</button><div><div class="eyebrow">BANNY CONTROL</div><h1>Админ-панель</h1><p class="muted">Магазин, пользователи, оплаты и поддержка</p></div></div>
  <div class="admin-stats"><div><b>${s.users||0}</b><small>Юзеров</small></div><div><b>${s.paid_users||0}</b><small>С доступом</small></div><div><b>${s.pending||0}</b><small>На проверке</small></div><div><b>${s.orders||0}</b><small>Заказов</small></div></div>
  <div class="admin-grid"><button onclick="adminChats()">💬<b>Чаты</b><small>Поддержка + unread</small></button><button onclick="adminUsers()">👥<b>Пользователи</b><small>Поиск и профили</small></button><button onclick="adminOrders()">🧾<b>Заказы</b><small>Оплаты и статусы</small></button><button onclick="categoriesPage()">🛒<b>Магазин</b><small>Товары и категории</small></button></div>`
}

async function adminUsers(){
  stopChatPolling();
  const r=await api('/api/admin/users');
  app.innerHTML=`<div class="admin-toolbar"><button class="back" onclick="adminHome()">← Админка</button><h1>Пользователи</h1><input id="usersSearch" class="input" placeholder="Поиск: имя, @username или ID" oninput="filterUsers(this.value)"></div><div id="usersList" class="list">${r.users.map(userRow).join('')||'<div class="empty">Пользователей нет.</div>'}</div>`;
}
function userRow(u){return `<div class="user-row" data-search="${esc([u.first_name,u.last_name,u.username,u.id].filter(Boolean).join(' ').toLowerCase())}" onclick="openChat(${u.id})"><div class="avatar small">${esc((u.first_name||u.username||'U')[0])}</div><div class="grow"><b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени')}</b><small>${u.username?'@'+esc(u.username)+' · ':''}ID ${u.id}${u.last_seen?' · '+esc(u.last_seen):''}</small>${u.last_message?`<small class="preview">${esc(u.last_message)}</small>`:''}</div>${u.unread?`<span class="unread">${u.unread}</span>`:''}<span class="status-dot ${u.has_access?'on':''}"></span></div>`}
function filterUsers(q){q=(q||'').toLowerCase().trim();document.querySelectorAll('#usersList .user-row').forEach(x=>x.style.display=x.dataset.search.includes(q)?'flex':'none')}

async function adminChats(){
  stopChatPolling();
  const r=await api('/api/admin/users');
  const users=[...r.users].sort((a,b)=>(b.unread-a.unread)||String(b.last_message_at||b.last_seen||'').localeCompare(String(a.last_message_at||a.last_seen||'')));
  app.innerHTML=`<div class="chat-layout"><aside class="chat-list"><div class="chat-top"><button class="back" onclick="adminHome()">←</button><div class="grow"><b>Чаты</b><small id="chatCount" class="muted">${users.length} диалогов</small></div></div><input id="chatSearch" class="input" placeholder="Поиск чата" oninput="filterChats(this.value)"><div id="chatUsers">${users.map(u=>chatUserRow(u)).join('')||'<div class="chat-empty">Диалогов пока нет</div>'}</div></aside><section class="chat-window" id="chatWindow"><div class="chat-empty">Выбери пользователя слева</div></section></div>`;
}
function chatUserRow(u){return `<div class="chat-user ${selectedChat===u.id?'selected':''}" data-search="${esc([u.first_name,u.last_name,u.username,u.id,u.last_message].filter(Boolean).join(' ').toLowerCase())}" onclick="openChat(${u.id})"><div class="avatar small">${esc((u.first_name||u.username||'U')[0])}</div><div class="grow"><div class="chat-user-line"><b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени')}</b>${u.last_message_at?`<time>${esc(u.last_message_at.slice(11,16))}</time>`:''}</div><small>${u.last_message?esc(u.last_message):(u.username?'@'+esc(u.username):'ID '+u.id)}</small></div>${u.unread?`<span class="unread">${u.unread}</span>`:''}</div>`}
function filterChats(q){q=(q||'').toLowerCase().trim();document.querySelectorAll('.chat-user').forEach(x=>x.style.display=x.dataset.search.includes(q)?'flex':'none')}

async function openChat(uid){
  selectedChat=uid;stopChatPolling();
  try{await api('/api/admin/chat/read',{method:'POST',body:JSON.stringify({user_id:uid})})}catch(e){}
  const r=await api('/api/admin/chats/'+uid);renderChat(r);startChatPolling();
}
function renderChat(r){
  const u=r.user||{};
  const name=[u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени';
  const avatar=(u.first_name||u.username||'U')[0];
  document.getElementById('chatWindow').innerHTML=`<div class="chat-header"><button class="back mobile-only" onclick="adminChats()">←</button><div class="avatar small">${esc(avatar)}</div><div class="grow"><b>${esc(name)}</b><small>${u.username?'@'+esc(u.username)+' · ':''}ID ${u.id} · ${u.has_access?'доступ есть':'доступа нет'}</small></div><button class="chat-info" onclick="showUserInfo(${u.id})">ⓘ</button></div><div id="messages" class="messages">${r.messages.map(messageBubble).join('')||'<div class="chat-empty">Сообщений пока нет</div>'}</div><form class="chat-compose" onsubmit="sendChat(event)"><button type="button" class="attach" title="Скоро">＋</button><input id="chatInput" class="input" autocomplete="off" placeholder="Сообщение..."><button class="btn primary compact">➤</button></form>`;
  scrollChat();
}
function messageBubble(m){const text=esc(m.text||'').replace(/\n/g,'<br>');const kind=m.kind&&m.kind!=='text'?`<span class="msg-kind">${esc(m.kind)}</span>`:'';return `<div class="bubble-wrap ${m.sender==='admin'?'out':'in'}"><div class="bubble">${kind}${text}<small>${esc(m.created_at||'')}</small></div></div>`}
function scrollChat(){const x=document.getElementById('messages');if(x)x.scrollTop=x.scrollHeight}
async function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text||!selectedChat)return;input.disabled=true;try{await api('/api/admin/chat/send',{method:'POST',body:JSON.stringify({user_id:selectedChat,text})});input.value='';await refreshOpenChat(false)}catch(err){alert('Не удалось отправить')}finally{input.disabled=false;input.focus()}}
async function refreshOpenChat(keepPosition=true){if(!selectedChat)return;try{const r=await api('/api/admin/chats/'+selectedChat);const box=document.getElementById('messages');if(!box)return;const wasBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=r.messages.map(messageBubble).join('')||'<div class="chat-empty">Сообщений пока нет</div>';if(!keepPosition||wasBottom)scrollChat();}catch(e){}}
function startChatPolling(){clearInterval(chatPoll);chatPoll=setInterval(async()=>{await refreshOpenChat(true);await refreshChatList();},2500)}
function stopChatPolling(){clearInterval(chatPoll);chatPoll=null;clearInterval(chatTimer);chatTimer=null}
async function refreshChatList(){const box=document.getElementById('chatUsers');if(!box)return;try{const r=await api('/api/admin/users');const q=(document.getElementById('chatSearch')?.value||'').toLowerCase().trim();const users=[...r.users].sort((a,b)=>(b.unread-a.unread)||String(b.last_message_at||b.last_seen||'').localeCompare(String(a.last_message_at||a.last_seen||'')));box.innerHTML=users.map(u=>chatUserRow(u)).join('')||'<div class="chat-empty">Диалогов пока нет</div>';filterChats(q)}catch(e){}}
async function showUserInfo(uid){try{const r=await api('/api/admin/chats/'+uid);const u=r.user||{};const orders=Object.values(await api('/api/admin/orders').then(x=>x.orders||[]).then(xs=>xs.filter(o=>Number(o.user_id)===Number(uid))));alert(`${[u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени'}\n${u.username?'@'+u.username+'\n':''}ID: ${u.id}\nДоступ: ${u.has_access?'есть':'нет'}\nПоследняя активность: ${u.last_seen||'—'}\nЗаказов: ${orders.length}`)}catch(e){}}

async function adminOrders(){
  stopChatPolling();
  const r=await api('/api/admin/orders');
  app.innerHTML=`<button class="back" onclick="adminHome()">← Админка</button><h1>Заказы</h1><div class="list">${r.orders.map(o=>`<div class="order-admin"><div class="order-admin-top"><b>${esc(o.title)}</b><span class="status-pill">${esc(o.status)}</span></div><small>${esc([o.first_name,o.username?'@'+o.username:''].filter(Boolean).join(' · '))} · ID ${o.user_id}</small><strong>${money(o.amount)}</strong><small>${esc(o.created_at||'')}</small></div>`).join('')||'<div class="empty">Заказов нет.</div>'}</div>`
}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>({home,categories:categoriesPage,purchases,promo:promoPage,profile}[b.dataset.tab])()));document.getElementById('closeBtn').onclick=()=>tg?.close?.();boot();
